@url = http://localhost:5000/api/identity
@accessToken = secret
@refreshToken = secret

# @password = sEcR3Twith8characters
@email = chadecloca@mywrld.site
@password = EEoTPqUOcu

###
POST {{url}}/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
POST {{url}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
GET {{url}}/me
Authorization: Bearer {{accessToken}}

###
POST {{url}}/refresh-tokens/use
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}",
}

###
POST {{url}}/refresh-tokens/revoke
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}",
}

###
POST {{url}}/access-tokens/revoke
Content-Type: application/json

{
  "accessToken": "{{accessToken}}",
}